// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDLJJyfeva9GayE15SA9PIUyW-tYSlGp0',
    appId: '1:435419844533:web:b2d542ce1dab2c99a693fc',
    messagingSenderId: '435419844533',
    projectId: 'immobilierapp-fd8a0',
    authDomain: 'immobilierapp-fd8a0.firebaseapp.com',
    storageBucket: 'immobilierapp-fd8a0.firebasestorage.app',
    measurementId: 'G-ZPBN6S3SF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAX6L919fEjPuNaDVG_4ZzSi80Wat5yoU',
    appId: '1:435419844533:android:ee66037c31ec4d3aa693fc',
    messagingSenderId: '435419844533',
    projectId: 'immobilierapp-fd8a0',
    storageBucket: 'immobilierapp-fd8a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwC05aocKBxd6wag5AC34v4wM_gErQ4Hk',
    appId: '1:435419844533:ios:ee9b078615b39fa8a693fc',
    messagingSenderId: '435419844533',
    projectId: 'immobilierapp-fd8a0',
    storageBucket: 'immobilierapp-fd8a0.firebasestorage.app',
    iosBundleId: 'com.example.immobilierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwC05aocKBxd6wag5AC34v4wM_gErQ4Hk',
    appId: '1:435419844533:ios:ee9b078615b39fa8a693fc',
    messagingSenderId: '435419844533',
    projectId: 'immobilierapp-fd8a0',
    storageBucket: 'immobilierapp-fd8a0.firebasestorage.app',
    iosBundleId: 'com.example.immobilierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDLJJyfeva9GayE15SA9PIUyW-tYSlGp0',
    appId: '1:435419844533:web:b47b58d0c3f0864da693fc',
    messagingSenderId: '435419844533',
    projectId: 'immobilierapp-fd8a0',
    authDomain: 'immobilierapp-fd8a0.firebaseapp.com',
    storageBucket: 'immobilierapp-fd8a0.firebasestorage.app',
    measurementId: 'G-1QSMPWLJ7B',
  );
}
